name: my first workflow
on: push
jobs:
  myfirstjob:
    runs-on: ubuntu-latest
    steps:
      - name: creating a report file
        run: "echo 'This is my first report file' > report.txt"
      
      - name: Upload report file
        uses: actions/upload-artifact@v3
        with:
          name: my-report
          push: report.txt