name: my first workflow
on: workflow_dispatch
jobs:
  myfirstjob:
    runs-on: ubuntu-latest
    steps:
      - name: clone repo
        run: git clone https://github.com/mayurimohite1710-dev/ACTION.git

      - name: check files in repo
        run: 
          cd ACTION/.github
          ls -la

      