name: CI-CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build step
        run: |
          echo "This is CI build output" > report.txt

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: report.txt

  cd:
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v5
        with:
          name: build-artifact

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu
            echo "Deploying artifact..."
            cat build-artifact/report.txt > deployed.txt
