name: my first workflow
on: push
jobs:
  myfirstjob:
    runs-on: ubuntu-latest
    steps:
      - name: clone repo
        run: action/checkout@v6
        steps:
          - name: list files
            run: ls -la

  mysecondjob:
    runs-on: ubuntu-latest
    steps:
          - name: install node js
            uses: actions/setup-node@v4
            with:
              node-version: '20'
          - name: check node js version
            run: node --version

        