name: my first workflow
on: push
jobs:
  myfirstjob:
    runs-on: ubuntu-latest
    steps:
      - name: creating a report file
        run: "echo 'This is my first report file' > report.txt"
      
      - name: Upload report file
        uses: actions/upload-artifact@v3
        with:
          name: my-report
          push: report.txt

  mysecondjob:
    runs-on: self hosted
    needs: myfirstjob
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: my-report

      - name: Check artifact content
        run: cat report.txt